#!/usr/bin/env python3
"""
Network Packet Analysis for Distributed Web Crawler
Uses Scapy to capture and analyze network traffic generated by the crawler
"""

import sys
import time
import threading
from collections import defaultdict, Counter
from datetime import datetime
import argparse
import signal
import json

try:
    from scapy.all import *
    from scapy.layers.http import HTTPRequest, HTTPResponse
    from scapy.layers.inet import IP, TCP, UDP
    from scapy.layers.dns import DNS, DNSQR, DNSRR
except ImportError:
    print("Error: Scapy not installed. Install with: pip install scapy")
    sys.exit(1)

class NetworkMonitor:
    """Network packet monitor for crawler traffic analysis"""
    
    def __init__(self, interface=None, duration=60, output_file=None):
        self.interface = interface or conf.iface
        self.duration = duration
        self.output_file = output_file
        self.running = False
        
        # Statistics tracking
        self.stats = {
            'total_packets': 0,
            'http_packets': 0,
            'https_packets': 0,
            'dns_packets': 0,
            'target_ips': Counter(),
            'target_domains': Counter(),
            'payload_sizes': [],
            'packet_types': Counter(),
            'start_time': None,
            'end_time': None
        }
        
        # Packet storage for detailed analysis
        self.captured_packets = []
        self.http_requests = []
        self.dns_queries = []
        
        # Setup signal handlers
        signal.signal(signal.SIGINT, self._signal_handler)
        signal.signal(signal.SIGTERM, self._signal_handler)
    
    def _signal_handler(self, signum, frame):
        """Handle shutdown signals"""
        print(f"\nReceived signal {signum}, stopping capture...")
        self.running = False
    
    def packet_handler(self, packet):
        """Process captured packets"""
        if not self.running:
            return
        
        self.stats['total_packets'] += 1
        timestamp = datetime.now()
        
        # Basic packet info
        packet_info = {
            'timestamp': timestamp.isoformat(),
            'size': len(packet),
            'protocol': 'Unknown'
        }
        
        # Process IP layer
        if IP in packet:
            packet_info['src_ip'] = packet[IP].src
            packet_info['dst_ip'] = packet[IP].dst
            packet_info['protocol'] = packet[IP].proto
            
            # Track target IPs (outbound connections)
            if packet[IP].dst != packet[IP].src:  # Not loopback
                self.stats['target_ips'][packet[IP].dst] += 1
        
        # Process TCP layer
        if TCP in packet:
            packet_info['src_port'] = packet[TCP].sport
            packet_info['dst_port'] = packet[TCP].dport
            packet_info['protocol'] = 'TCP'
            
            # HTTP traffic (port 80)
            if packet[TCP].dport == 80 or packet[TCP].sport == 80:
                self.stats['http_packets'] += 1
                packet_info['protocol'] = 'HTTP'
                self._process_http_packet(packet, packet_info)
            
            # HTTPS traffic (port 443)
            elif packet[TCP].dport == 443 or packet[TCP].sport == 443:
                self.stats['https_packets'] += 1
                packet_info['protocol'] = 'HTTPS'
        
        # Process UDP layer
        elif UDP in packet:
            packet_info['src_port'] = packet[UDP].sport
            packet_info['dst_port'] = packet[UDP].dport
            packet_info['protocol'] = 'UDP'
            
            # DNS traffic (port 53)
            if packet[UDP].dport == 53 or packet[UDP].sport == 53:
                self.stats['dns_packets'] += 1
                packet_info['protocol'] = 'DNS'
                self._process_dns_packet(packet, packet_info)
        
        # Track payload sizes
        if Raw in packet:
            payload_size = len(packet[Raw])
            packet_info['payload_size'] = payload_size
            self.stats['payload_sizes'].append(payload_size)
        
        # Track packet types
        self.stats['packet_types'][packet_info['protocol']] += 1
        
        # Store packet for detailed analysis (limit to last 1000)
        self.captured_packets.append(packet_info)
        if len(self.captured_packets) > 1000:
            self.captured_packets.pop(0)
    
    def _process_http_packet(self, packet, packet_info):
        """Process HTTP packet details"""
        try:
            if HTTPRequest in packet:
                http_info = {
                    'timestamp': packet_info['timestamp'],
                    'method': packet[HTTPRequest].Method.decode() if packet[HTTPRequest].Method else 'Unknown',
                    'host': packet[HTTPRequest].Host.decode() if packet[HTTPRequest].Host else 'Unknown',
                    'path': packet[HTTPRequest].Path.decode() if packet[HTTPRequest].Path else '/',
                    'user_agent': packet[HTTPRequest].User_Agent.decode() if hasattr(packet[HTTPRequest], 'User_Agent') and packet[HTTPRequest].User_Agent else 'Unknown',
                    'src_ip': packet_info.get('src_ip'),
                    'dst_ip': packet_info.get('dst_ip')
                }
                
                self.http_requests.append(http_info)
                
                # Track target domains
                if http_info['host'] != 'Unknown':
                    self.stats['target_domains'][http_info['host']] += 1
                
                print(f"[HTTP] {http_info['method']} {http_info['host']}{http_info['path']}")
            
            elif HTTPResponse in packet:
                packet_info['http_status'] = packet[HTTPResponse].Status_Code
                print(f"[HTTP] Response: {packet[HTTPResponse].Status_Code}")
                
        except Exception as e:
            pass  # Silently ignore HTTP parsing errors
    
    def _process_dns_packet(self, packet, packet_info):
        """Process DNS packet details"""
        try:
            if DNS in packet and DNSQR in packet:
                dns_info = {
                    'timestamp': packet_info['timestamp'],
                    'query_name': packet[DNSQR].qname.decode() if packet[DNSQR].qname else 'Unknown',
                    'query_type': packet[DNSQR].qtype,
                    'src_ip': packet_info.get('src_ip'),
                    'dst_ip': packet_info.get('dst_ip')
                }
                
                self.dns_queries.append(dns_info)
                
                # Track target domains from DNS queries
                if dns_info['query_name'] != 'Unknown':
                    clean_name = dns_info['query_name'].rstrip('.')
                    self.stats['target_domains'][clean_name] += 1
                
                print(f"[DNS] Query: {dns_info['query_name']}")
                
        except Exception as e:
            pass  # Silently ignore DNS parsing errors
    
    def start_capture(self):
        """Start packet capture"""
        print(f"Starting network monitor on interface: {self.interface}")
        print(f"Capture duration: {self.duration} seconds")
        print(f"Filtering crawler traffic (HTTP/HTTPS/DNS)")
        print("Press Ctrl+C to stop early...")
        
        self.running = True
        self.stats['start_time'] = datetime.now()
        
        # Start capture in a separate thread
        capture_thread = threading.Thread(target=self._capture_loop)
        capture_thread.start()
        
        # Wait for specified duration or until stopped
        start_time = time.time()
        while self.running and (time.time() - start_time) < self.duration:
            time.sleep(1)
            remaining = int(self.duration - (time.time() - start_time))
            if remaining > 0 and remaining % 10 == 0:
                print(f"Capturing... {remaining} seconds remaining")
        
        self.running = False
        capture_thread.join()
        
        self.stats['end_time'] = datetime.now()
        print("\nCapture completed!")
    
    def _capture_loop(self):
        """Main capture loop"""
        try:
            # Filter for HTTP/HTTPS/DNS traffic
            filter_expr = "(tcp port 80 or tcp port 443 or udp port 53)"
            
            sniff(
                iface=self.interface,
                prn=self.packet_handler,
                filter=filter_expr,
                stop_filter=lambda x: not self.running,
                store=False  # Don't store packets in memory
            )
        except Exception as e:
            print(f"Capture error: {e}")
            self.running = False
    
    def print_summary(self):
        """Print capture summary"""
        if not self.stats['start_time']:
            print("No capture data available")
            return
        
        duration = (self.stats['end_time'] - self.stats['start_time']).total_seconds()
        
        print("\n" + "="*60)
        print("NETWORK CAPTURE SUMMARY")
        print("="*60)
        
        print(f"\n📊 CAPTURE STATISTICS:")
        print(f"  Duration: {duration:.2f} seconds")
        print(f"  Total Packets: {self.stats['total_packets']}")
        print(f"  HTTP Packets: {self.stats['http_packets']}")
        print(f"  HTTPS Packets: {self.stats['https_packets']}")
        print(f"  DNS Packets: {self.stats['dns_packets']}")
        
        if self.stats['total_packets'] > 0:
            pps = self.stats['total_packets'] / duration
            print(f"  Packets/Second: {pps:.2f}")
        
        print(f"\n🎯 TARGET ANALYSIS:")
        if self.stats['target_ips']:
            print(f"  Unique Target IPs: {len(self.stats['target_ips'])}")
            print("  Top 5 Target IPs:")
            for ip, count in self.stats['target_ips'].most_common(5):
                print(f"    {ip}: {count} packets")
        
        if self.stats['target_domains']:
            print(f"  Unique Target Domains: {len(self.stats['target_domains'])}")
            print("  Top 5 Target Domains:")
            for domain, count in self.stats['target_domains'].most_common(5):
                print(f"    {domain}: {count} requests")
        
        print(f"\n📦 PAYLOAD ANALYSIS:")
        if self.stats['payload_sizes']:
            avg_size = sum(self.stats['payload_sizes']) / len(self.stats['payload_sizes'])
            max_size = max(self.stats['payload_sizes'])
            min_size = min(self.stats['payload_sizes'])
            print(f"  Average Payload Size: {avg_size:.2f} bytes")
            print(f"  Max Payload Size: {max_size} bytes")
            print(f"  Min Payload Size: {min_size} bytes")
        
        print(f"\n🔍 PROTOCOL BREAKDOWN:")
        for protocol, count in self.stats['packet_types'].most_common():
            percentage = (count / self.stats['total_packets']) * 100
            print(f"  {protocol}: {count} packets ({percentage:.1f}%)")
        
        print(f"\n🌐 HTTP REQUESTS:")
        if self.http_requests:
            print(f"  Total HTTP Requests: {len(self.http_requests)}")
            
            # Count by method
            methods = Counter([req['method'] for req in self.http_requests])
            print("  HTTP Methods:")
            for method, count in methods.most_common():
                print(f"    {method}: {count}")
            
            # Count by host
            hosts = Counter([req['host'] for req in self.http_requests if req['host'] != 'Unknown'])
            print("  Top HTTP Hosts:")
            for host, count in hosts.most_common(5):
                print(f"    {host}: {count} requests")
        
        print(f"\n🔍 DNS QUERIES:")
        if self.dns_queries:
            print(f"  Total DNS Queries: {len(self.dns_queries)}")
            print("  Top Queried Domains:")
            queries = Counter([query['query_name'] for query in self.dns_queries if query['query_name'] != 'Unknown'])
            for domain, count in queries.most_common(5):
                print(f"    {domain}: {count} queries")
    
    def save_results(self):
        """Save capture results to file"""
        if not self.output_file:
            return
        
        results = {
            'capture_info': {
                'interface': self.interface,
                'start_time': self.stats['start_time'].isoformat() if self.stats['start_time'] else None,
                'end_time': self.stats['end_time'].isoformat() if self.stats['end_time'] else None,
                'duration': (self.stats['end_time'] - self.stats['start_time']).total_seconds() if self.stats['start_time'] else 0
            },
            'statistics': {
                'total_packets': self.stats['total_packets'],
                'http_packets': self.stats['http_packets'],
                'https_packets': self.stats['https_packets'],
                'dns_packets': self.stats['dns_packets'],
                'target_ips': dict(self.stats['target_ips']),
                'target_domains': dict(self.stats['target_domains']),
                'packet_types': dict(self.stats['packet_types'])
            },
            'payload_analysis': {
                'sizes': self.stats['payload_sizes'],
                'average_size': sum(self.stats['payload_sizes']) / len(self.stats['payload_sizes']) if self.stats['payload_sizes'] else 0,
                'max_size': max(self.stats['payload_sizes']) if self.stats['payload_sizes'] else 0,
                'min_size': min(self.stats['payload_sizes']) if self.stats['payload_sizes'] else 0
            },
            'http_requests': self.http_requests[-50:],  # Last 50 requests
            'dns_queries': self.dns_queries[-50:],  # Last 50 queries
            'sample_packets': self.captured_packets[-100:]  # Last 100 packets
        }
        
        try:
            with open(self.output_file, 'w') as f:
                json.dump(results, f, indent=2, default=str)
            print(f"\n💾 Results saved to: {self.output_file}")
        except Exception as e:
            print(f"Error saving results: {e}")


def main():
    """Main function"""
    parser = argparse.ArgumentParser(description='Network monitor for crawler traffic')
    parser.add_argument('-i', '--interface', help='Network interface to monitor')
    parser.add_argument('-d', '--duration', type=int, default=60, 
                       help='Capture duration in seconds (default: 60)')
    parser.add_argument('-o', '--output', help='Output file for results (JSON)')
    parser.add_argument('-l', '--list-interfaces', action='store_true',
                       help='List available network interfaces')
    
    args = parser.parse_args()
    
    # List interfaces if requested
    if args.list_interfaces:
        print("Available network interfaces:")
        ifaces = get_if_list()
        for iface in ifaces:
            print(f"  - {iface}")
        return
    
    # Check if running with appropriate privileges
    try:
        get_if_list()
    except PermissionError:
        print("Error: This script requires root/administrator privileges to capture packets.")
        print("Try running with: sudo python3 network_monitor.py")
        sys.exit(1)
    
    # Create and run monitor
    monitor = NetworkMonitor(
        interface=args.interface,
        duration=args.duration,
        output_file=args.output
    )
    
    try:
        monitor.start_capture()
        monitor.print_summary()
        monitor.save_results()
    except KeyboardInterrupt:
        print("\nCapture interrupted by user")
        monitor.print_summary()
        monitor.save_results()
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
